<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-E771N59" failures="1" tests="6" name="DDStoreTest" time="22.624" errors="0" timestamp="2025-03-19T14:38:52 IST">
  <testcase classname="api.test.DDStoreTests" name="testPostUser" time="5.33"/>
  <testcase classname="api.test.DDStoreTests" name="testPostUser" time="2.253"/>
  <testcase classname="api.test.DDStoreTests" name="testPostUser" time="2.961"/>
  <testcase classname="api.test.DDStoreTests" name="testDeleteOrderByOrderId" time="3.084">
    <failure type="java.lang.AssertionError" message="expected [200] but found [404]">
      <![CDATA[java.lang.AssertionError: expected [200] but found [404]
at api.test.DDStoreTests.testDeleteOrderByOrderId(DDStoreTests.java:38)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1596)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testDeleteOrderByOrderId -->
  <testcase classname="api.test.DDStoreTests" name="testDeleteOrderByOrderId" time="3.566"/>
  <testcase classname="api.test.DDStoreTests" name="testDeleteOrderByOrderId" time="3.077"/>
</testsuite> <!-- DDStoreTest -->
